version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code/
    ports:
      - '8000:8000'
    env_file:
      - backend/.env
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    restart: always
    env_file:
      - backend/.env
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    container_name: pgdb
    ports:
      - '5432:5432'
    volumes:
      - pgdbData:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          memory: "1500M"
        reservations:
          cpus: "0.25"
          memory: "128M"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - pgdb
    ports:
      - "5051:80"
    volumes:
      - pgAdminData:/var/lib/pgadmin
    env_file:
      - backend/.env
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    restart: always

volumes:
  pgdbData: null
  pgAdminData: null