version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: board_games
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./board_games/:/code/
    ports:
      - '8000:8000'
    env_file:
      - ./board_games/.env
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=board_games_dev
      - POSTGRES_USER=board_games
      - POSTGRES_PASSWORD=board_games
    container_name: pgdb
    ports:
      - '5432:5432'
    env_file:
      - ./board_games/.env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          memory: "1500M"
        reservations:
          cpus: "0.25"
          memory: "128M"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - pgdb
    ports:
      - "5051:80"
#    volumes:
#      - pgAdminData:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always

volumes:
  pgdbdata: null