# Generated by Django 5.0.1 on 2024-02-07 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(default=datetime.date(2024, 2, 15)),
        ),
    ]
