# Generated by Django 5.0.1 on 2024-02-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='closing_date',
            field=models.DateField(null=True),
        ),
    ]
