# Generated by Django 5.0.1 on 2024-02-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_action', '0002_alter_booking_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('view_booking_filtered', 'Can view filtered booking')]},
        ),
    ]
