# Generated by Django 5.0.1 on 2024-02-11 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action', '0002_alter_booking_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(default=datetime.date(2024, 2, 18)),
        ),
    ]
