# Generated by Django 5.0.1 on 2024-02-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_action', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('view_filtered_booking', 'Can view filtered booking')]},
        ),
    ]
