# Generated by Django 5.0.1 on 2024-02-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_boardgame_description'),
        ('user_action', '0003_alter_booking_closing_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardGame',
            new_name='Game',
        ),
    ]
