# Generated by Django 5.0.1 on 2024-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
