# Generated by Django 5.0.1 on 2024-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_cover_photo_game_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='n_players',
            field=models.TextField(verbose_name='number of players'),
        ),
    ]
