# Generated by Django 5.0.1 on 2024-02-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_itempurchase_item_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempurchase',
            name='status',
        ),
    ]
