# Generated by Django 5.0.1 on 2024-02-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action', '0002_alter_booking_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(),
        ),
    ]
