# Generated by Django 5.0.1 on 2024-02-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_bookeddate_gameitem'),
        ('user_action', '0003_alter_booking_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='game_item',
            field=models.ForeignKey(default='0ea7e325-2434-455b-9e19-8f9811d228c9', on_delete=django.db.models.deletion.CASCADE, to='game.gameitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='opening_date',
            field=models.DateField(),
        ),
    ]
