# Generated by Django 5.0.1 on 2024-02-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempurchase',
            name='item_uuid',
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='status',
            field=models.CharField(choices=[('PN', 'PENDING'), ('PD', 'PAID')], max_length=50),
        ),
    ]
