# Generated by Django 5.0.1 on 2024-03-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_itempurchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_data',
            field=models.TextField(default='delivery blank data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_service',
            field=models.CharField(default='delivery blank service', max_length=50),
            preserve_default=False,
        ),
    ]
