# Generated by Django 5.0.1 on 2024-02-11 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('payment_type', models.CharField(max_length=50, verbose_name='type_of_payment')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutData',
            fields=[
                ('user_uuid', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payout_data', serialize=False, to='payment_account.account', to_field='user_uuid')),
                ('account_number', models.CharField(max_length=30)),
                ('is_auto_payout', models.BooleanField(default=False)),
                ('payout_type', models.CharField(choices=[('bank_card', 'BANK_CARD'), ('yoo_money', 'YOO_MONEY')], max_length=23)),
            ],
        ),
        migrations.AddConstraint(
            model_name='payoutdata',
            constraint=models.UniqueConstraint(fields=('account_number', 'payout_type'), name='unique payout data'),
        ),
    ]
