# Generated by Django 5.0.1 on 2024-02-11 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_account', '0002_paymentcommission_payoutdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcommission',
            old_name='name',
            new_name='payment_service',
        ),
    ]
