# Generated by Django 5.0.1 on 2024-02-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_profile_info', 'Can view profile information')]},
        ),
    ]
