# Generated by Django 5.0.1 on 2024-01-31 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
    ]
